/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EvaBaseServerBotInterface extends ethers.utils.Interface {
  functions: {
    "checkUpkeep(bytes)": FunctionFragment;
    "config()": FunctionFragment;
    "encodeTwoArr(uint256[],bytes[])": FunctionFragment;
    "encodeUintAndBytes(bytes,uint256)": FunctionFragment;
    "encodeUints(uint256[])": FunctionFragment;
    "evaFlowChecker()": FunctionFragment;
    "keepBotId()": FunctionFragment;
    "keeps(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "performUpkeep(bytes)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setEBSKeepStatus(address,bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "encodeTwoArr",
    values: [BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeUintAndBytes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeUints",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "evaFlowChecker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "keepBotId", values?: undefined): string;
  encodeFunctionData(functionFragment: "keeps", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEBSKeepStatus",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "encodeTwoArr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeUintAndBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeUints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaFlowChecker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keepBotId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keeps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEBSKeepStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "SetEBSKeepStatus(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetEBSKeepStatus"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type SetEBSKeepStatusEvent = TypedEvent<
  [string, boolean] & { user: string; status: boolean }
>;

export class EvaBaseServerBot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EvaBaseServerBotInterface;

  functions: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    config(overrides?: CallOverrides): Promise<[string]>;

    encodeTwoArr(
      _uint: BigNumberish[],
      _bytes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    encodeUintAndBytes(
      _bytes: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    encodeUints(
      _uint: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    evaFlowChecker(overrides?: CallOverrides): Promise<[string]>;

    keepBotId(overrides?: CallOverrides): Promise<[number]>;

    keeps(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEBSKeepStatus(
      keep: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  checkUpkeep(
    checkData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  config(overrides?: CallOverrides): Promise<string>;

  encodeTwoArr(
    _uint: BigNumberish[],
    _bytes: BytesLike[],
    overrides?: CallOverrides
  ): Promise<string>;

  encodeUintAndBytes(
    _bytes: BytesLike,
    _value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  encodeUints(
    _uint: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<string>;

  evaFlowChecker(overrides?: CallOverrides): Promise<string>;

  keepBotId(overrides?: CallOverrides): Promise<number>;

  keeps(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  performUpkeep(
    performData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEBSKeepStatus(
    keep: string,
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    config(overrides?: CallOverrides): Promise<string>;

    encodeTwoArr(
      _uint: BigNumberish[],
      _bytes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    encodeUintAndBytes(
      _bytes: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    encodeUints(
      _uint: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    evaFlowChecker(overrides?: CallOverrides): Promise<string>;

    keepBotId(overrides?: CallOverrides): Promise<number>;

    keeps(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    performUpkeep(
      performData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setEBSKeepStatus(
      keep: string,
      status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "SetEBSKeepStatus(address,bool)"(
      user?: string | null,
      status?: null
    ): TypedEventFilter<[string, boolean], { user: string; status: boolean }>;

    SetEBSKeepStatus(
      user?: string | null,
      status?: null
    ): TypedEventFilter<[string, boolean], { user: string; status: boolean }>;
  };

  estimateGas: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    encodeTwoArr(
      _uint: BigNumberish[],
      _bytes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeUintAndBytes(
      _bytes: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeUints(
      _uint: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    evaFlowChecker(overrides?: CallOverrides): Promise<BigNumber>;

    keepBotId(overrides?: CallOverrides): Promise<BigNumber>;

    keeps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEBSKeepStatus(
      keep: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    encodeTwoArr(
      _uint: BigNumberish[],
      _bytes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeUintAndBytes(
      _bytes: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeUints(
      _uint: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    evaFlowChecker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keepBotId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keeps(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEBSKeepStatus(
      keep: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
