/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EvaSafesFactoryInterface extends ethers.utils.Interface {
  functions: {
    "allWallets(uint256)": FunctionFragment;
    "calcSafes(address)": FunctionFragment;
    "changeConfig(address)": FunctionFragment;
    "codeHash()": FunctionFragment;
    "config()": FunctionFragment;
    "create(address)": FunctionFragment;
    "evaSafesMap(address)": FunctionFragment;
    "get(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allWallets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "calcSafes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "changeConfig",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "codeHash", values?: undefined): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(functionFragment: "create", values: [string]): string;
  encodeFunctionData(functionFragment: "evaSafesMap", values: [string]): string;
  encodeFunctionData(functionFragment: "get", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allWallets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "calcSafes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "codeHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evaSafesMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "WalletCreated(address,address,uint256)": EventFragment;
    "configChanged(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WalletCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "configChanged"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type WalletCreatedEvent = TypedEvent<
  [string, string, BigNumber] & {
    user: string;
    wallet: string;
    arg2: BigNumber;
  }
>;

export type configChangedEvent = TypedEvent<[string] & { newConfig: string }>;

export class EvaSafesFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EvaSafesFactoryInterface;

  functions: {
    allWallets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    calcSafes(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string] & { wallet: string }>;

    changeConfig(
      _config: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    codeHash(overrides?: CallOverrides): Promise<[string]>;

    config(overrides?: CallOverrides): Promise<[string]>;

    create(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    evaSafesMap(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    get(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string] & { wallet: string }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allWallets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  calcSafes(user: string, overrides?: CallOverrides): Promise<string>;

  changeConfig(
    _config: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  codeHash(overrides?: CallOverrides): Promise<string>;

  config(overrides?: CallOverrides): Promise<string>;

  create(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  evaSafesMap(arg0: string, overrides?: CallOverrides): Promise<string>;

  get(user: string, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allWallets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    calcSafes(user: string, overrides?: CallOverrides): Promise<string>;

    changeConfig(_config: string, overrides?: CallOverrides): Promise<void>;

    codeHash(overrides?: CallOverrides): Promise<string>;

    config(overrides?: CallOverrides): Promise<string>;

    create(user: string, overrides?: CallOverrides): Promise<string>;

    evaSafesMap(arg0: string, overrides?: CallOverrides): Promise<string>;

    get(user: string, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "WalletCreated(address,address,uint256)"(
      user?: string | null,
      wallet?: null,
      undefined?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { user: string; wallet: string; arg2: BigNumber }
    >;

    WalletCreated(
      user?: string | null,
      wallet?: null,
      undefined?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { user: string; wallet: string; arg2: BigNumber }
    >;

    "configChanged(address)"(
      newConfig?: string | null
    ): TypedEventFilter<[string], { newConfig: string }>;

    configChanged(
      newConfig?: string | null
    ): TypedEventFilter<[string], { newConfig: string }>;
  };

  estimateGas: {
    allWallets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcSafes(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    changeConfig(
      _config: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    codeHash(overrides?: CallOverrides): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    create(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    evaSafesMap(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    get(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allWallets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcSafes(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeConfig(
      _config: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    codeHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    create(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    evaSafesMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get(user: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
