/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface UpkeepRegistrationRequestsInterfaceInterface
  extends ethers.utils.Interface {
  functions: {
    "getPendingRequest(bytes32)": FunctionFragment;
    "register(string,bytes,address,uint32,address,bytes,uint96,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getPendingRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [
      string,
      BytesLike,
      string,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {};
}

export class UpkeepRegistrationRequestsInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UpkeepRegistrationRequestsInterfaceInterface;

  functions: {
    getPendingRequest(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    register(
      name: string,
      encryptedEmail: BytesLike,
      upkeepContract: string,
      gasLimit: BigNumberish,
      adminAddress: string,
      checkData: BytesLike,
      amount: BigNumberish,
      source: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getPendingRequest(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber]>;

  register(
    name: string,
    encryptedEmail: BytesLike,
    upkeepContract: string,
    gasLimit: BigNumberish,
    adminAddress: string,
    checkData: BytesLike,
    amount: BigNumberish,
    source: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPendingRequest(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    register(
      name: string,
      encryptedEmail: BytesLike,
      upkeepContract: string,
      gasLimit: BigNumberish,
      adminAddress: string,
      checkData: BytesLike,
      amount: BigNumberish,
      source: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getPendingRequest(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(
      name: string,
      encryptedEmail: BytesLike,
      upkeepContract: string,
      gasLimit: BigNumberish,
      adminAddress: string,
      checkData: BytesLike,
      amount: BigNumberish,
      source: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPendingRequest(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      name: string,
      encryptedEmail: BytesLike,
      upkeepContract: string,
      gasLimit: BigNumberish,
      adminAddress: string,
      checkData: BytesLike,
      amount: BigNumberish,
      source: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
