/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  EvaKeepBotBase,
  EvaKeepBotBaseInterface,
} from "../EvaKeepBotBase";

const _abi = [
  {
    inputs: [],
    name: "config",
    outputs: [
      {
        internalType: "contract IEvabaseConfig",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "evaFlowChecker",
    outputs: [
      {
        internalType: "contract EvaFlowChecker",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class EvaKeepBotBase__factory {
  static readonly abi = _abi;
  static createInterface(): EvaKeepBotBaseInterface {
    return new utils.Interface(_abi) as EvaKeepBotBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EvaKeepBotBase {
    return new Contract(address, _abi, signerOrProvider) as EvaKeepBotBase;
  }
}
